spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xbshop?characterEncoding=utf-8&serverTimezone=Hongkong


  redis:
    password: 123456
    port: 6379
    host: 127.0.0.1

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true


  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.xb.entity

file:
  requestPath: /upload/**
  dir: D:/upload/









